### ISSUE TITLE
Clicking on the "import" button throws an exception

### ISSUE THREAD

**Issue by filliravaz** [didas72/COTWSaveManager#4]
<img width="320" alt="image" src="https://github.com/didas72/COTWSaveManager/assets/40716956/a2da877f-58a0-419e-9f16-ed6adab765d3">

This is the exception text from the popup
```
************** Exception Text **************
System.ArgumentException: Filter string you provided is not valid. The filter string must contain a description of the filter, followed by the vertical bar (|) and the filter pattern. The strings for different filtering options must also be separated by the vertical bar. Example: "Text files (*.txt)|*.txt|All files (*.*)|*.*"
   at System.Windows.Forms.FileDialog.set_Filter(String value)
   at COTWSaveManager.MainForm.BackupImportButton_Click(Object sender, EventArgs e) in E:\dev\C#\COTWSaveManager\COTWSaveManager\Form1.cs:line 262
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

Am I doing something wrong?

**Comment by didas72** [comment]
Will take a look, thank you for reporting

**Comment by didas72** [comment]
Found the issue and patched it. Now uploading as v1.6.1
Thank you so much for taking the time to report it and for including all the information.
